project_id = "nylzapcjghsujvtmmkpv"

[functions.delete-user]
verify_jwt = true

[functions.admin-create-review]
verify_jwt = true

[functions.impersonate-user]
verify_jwt = false

[functions.resolve-referral]
verify_jwt = false

[functions.resolve-referrals]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.send-kyc-email]
verify_jwt = true

[functions.send-withdrawal-email]
verify_jwt = true

[functions.migrate-commissions]
verify_jwt = true